---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

This website hosts Riley's honours data analysis. The cleaning, plotting, analysis process is documented in the .Rmd files below. 

# 1. Cleaning
- [clean emg data for adult face](1_clean_emg_adult.html)
- [clean emg data for child faces](2_clean_emg_child.html)
- [combine cleaned child and adult data](3_combine_clean_adult_child.html)
- [clean baseline](4_clean_baseline.html)
- [calculate zscores](5_calculating_zscores.html)
- [deal wih bin outliers](6_bin_outliers.html)

# 2. Plotting

- [plotting cheek and brow activity in response to child and adult faces](7_plotting.html)

# 3. Analysis

- [first models- emotion, bin, emotion*bin with random intercepts for participant and trial](8_analysing.html)
- [cheek analysis take 2- code check](9_cheek_analysis.html)
-- take 2 updated 9:30am 7-9-2020, just child cheek happy angry

# Riley is doing analysis 

